self: super:

{
  emacsPackages = super.emacsPackages.overrideScope' (self': super': rec {
    nixStraightOverrides = inputs:
      self'.trivialBuild rec {
        pname = "nix-straight-overrides";
        ename = pname;
        src = curSrc;
        curSrc = builtins.toFile "nix-straight-overrides.el"
          ''
            ;;; nix-straight-overrides.el --- Summary:

            ;; Override supplied packages as built-in.

            ;;; Commentary:

            ;; This file was automatically generated by nix.

            ;;; Code:

            (dolist (p '(${self.lib.concatStringsSep " " (map (p: p.pname) inputs)}))
              (straight-override-recipe `(,p :type built-in)))

            (provide 'nix-straight-overrides)

            ;;; nix-straight-overrides ends here
          '' ;
      };
    withStraightOverrides = inputs: [ (nixStraightOverrides inputs) ] ++ inputs;
  });
}
